### PR TITLE
Replace void with undefined in Web IDL

### PR DESCRIPTION
**Pull request by foolip**
See https://github.com/heycam/webidl/pull/906.

### CODE REVIEW

**Comment by foolip** [comment]
@saschanaz FYI

**Comment by saschanaz** [comment]
I wonder anyone really have any interest here, since there has been no real editor work?

**Comment by foolip** [comment]
@saschanaz this API has shipped so it does belong in browser-specs, if you mean that an alternative would be to drop it from there.

@jakearchibald can you help get this merged?

**Comment by saschanaz** [comment]
Or @sideshowbarker who committed last.

**Comment by saschanaz** [comment]
BTW could you add "closes #7" to autoclose the duplication? (I can manually close it, but the current logic will reopen it every Monday)

**Comment by saschanaz** [comment]
Thanks @sideshowbarker! If you have time please also merge #4 and #5 which are also about IDL 👍.

**Pull request merged**
