### PR TITLE
Move Periodic BackgroundSync content from WICG/BackgroundSync repo.

### PR DESCRIPTION
**Pull request by mugdhalakhani**
@yoavweiss @jakearchibald, PTAL.
I've dropped use-cases.md from WICG/BackgroundSync since it doesn't have anything the explainer doesn't already talk about.

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
Can we please `git mv` the `index.bs` and `index.html` files up into the repo root (that is, out of `spec` subdirectory)? If we keep those in that `spec` subdirectory, then the published spec will be served from `https://wicg.github.io/periodic-background-sync/spec/` rather than just `https://wicg.github.io/periodic-background-sync/`. (Just as the spec was previously published at `https://wicg.github.io/BackgroundSync/spec/`…)

**Review by yoavweiss — COMMENTED** [review]
RSLGTM assuming this is a simple copy from the other repo

**Comment by mugdhalakhani** [comment]
Thanks both! I have removed the spec directory.

**Comment by sideshowbarker** [comment]
What’s the plan for the https://github.com/WICG/BackgroundSync repo now? Do we want to archive that now, or delete it, or what?

Note that the way this PR was done, we basically lose the git history for the `index.bs` source and other documents. Is that OK?

Why not just instead simply rename the https://github.com/WICG/BackgroundSync to https://github.com/WICG/periodic-background-sync/?

**Comment by yoavweiss** [comment]
@sideshowbarker https://github.com/WICG/BackgroundSync will have the BackgroundSync spec, where this new repo will contain the (different) Periodic Background Sync.

**Comment by sideshowbarker** [comment]
> @sideshowbarker https://github.com/WICG/BackgroundSync will have the BackgroundSync spec, where this new repo will contain the (different) Periodic Background Sync.

aha — thanks, I see now

**Comment by mugdhalakhani** [comment]
To keep the git history and comments, I'll keep WICG/BackgroundSync/spec/PeriodicBackgroundSync-index.html and make it a placeholder that points to https://wicg.github.io/periodic-background-sync

**Pull request merged**
